# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

# 忽略所有pods的警告
inhibit_all_warnings!
target 'TQLClassifyScrollVCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TQLClassifyScrollVCDemo
   #pod 'TQLClassifyScrollVC'
   
 #pod 'TQLClassifyScrollVC', :path =>'./TQLClassifyScrollVC'

end
